services:
  - type: web
    name: ultraviolet-proxy
    runtime: node
    plan: pro
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: 26.9.0
